FROM node:carbon

# Create app directory
WORKDIR /ccbd_project

# Copy source code
COPY . .


# Install dependencies
RUN cd implementation-2 && npm install
RUN cd implementation-3 && npm install
RUN cd implementation-4 && npm install
RUN cd implementation-5 && npm install
